<?php
/**
 * ACF Block Fields
 *
 * Includes:
 *   Block: Field
 *   Block: Form
 *   Block: Form Data
 *   Block: Form Meta
 *   Block: Select
 *   Block: Checkbox
 *   Block: Input
 *   Options
 *   Conditional Logic
 *
 * @package ACFFormBlocks
 */

add_action(
	'acf/include_fields',
	function() {
		add_action( 'acf/include_fields', function() {
			if ( ! function_exists( 'acf_add_local_field_group' ) ) {
				return;
			}

			acf_add_local_field_group( array(
				'key' => 'group_6683facdcf97c',
				'title' => 'Block: Field',
				'fields' => array(
					array(
						'key' => 'field_6683facee1fbc',
						'label' => 'Placeholder',
						'name' => 'placeholder',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/input',
						),
					),
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/textarea',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_668327fbcea85',
				'title' => 'Block: Form',
				'fields' => array(
					array(
						'key' => 'field_6684014a8bd1f',
						'label' => 'Form Settings',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 1,
						'multi_expand' => 1,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_668327fcca5b6',
						'label' => 'Form Method',
						'name' => 'method',
						'aria-label' => '',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'POST' => 'POST',
							'GET' => 'GET',
							'DIALOG' => 'DIALOG',
						),
						'default_value' => 'POST',
						'return_format' => 'value',
						'allow_null' => 0,
						'layout' => 'horizontal',
					),
					array(
						'key' => 'field_6684017c8bd20',
						'label' => 'Submission',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 1,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_66992c02d61ed',
						'label' => 'Save to Database?',
						'name' => 'save_data',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_66832f771e208',
						'label' => 'Confirmation',
						'name' => 'confirmation',
						'aria-label' => '',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'message' => 'Message',
							'redirect' => 'Redirect',
							'content' => 'Page Content',
						),
						'default_value' => 'message',
						'return_format' => 'value',
						'allow_null' => 0,
						'layout' => 'horizontal',
					),
					array(
						'key' => 'field_66832f9c1e209',
						'label' => 'Message',
						'name' => 'message',
						'aria-label' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66832f771e208',
									'operator' => '==',
									'value' => 'message',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Thank you for your submission!',
						'maxlength' => '',
						'rows' => '',
						'placeholder' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_668952d3e1d7f',
						'label' => 'Page',
						'name' => 'page',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66832f771e208',
									'operator' => '==',
									'value' => 'redirect',
								),
								array(
									'field' => 'field_66895376e1d81',
									'operator' => '!=',
									'value' => '1',
								),
							),
							array(
								array(
									'field' => 'field_66832f771e208',
									'operator' => '==',
									'value' => 'content',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'page',
						),
						'post_status' => '',
						'taxonomy' => '',
						'return_format' => 'object',
						'multiple' => 0,
						'allow_null' => 0,
						'bidirectional' => 0,
						'ui' => 1,
						'bidirectional_target' => array(
						),
					),
					array(
						'key' => 'field_66895376e1d81',
						'label' => 'Custom URL',
						'name' => 'custom_url',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66832f771e208',
									'operator' => '==',
									'value' => 'redirect',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_66832fbc1e20a',
						'label' => 'Redirect URL',
						'name' => 'redirect',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66832f771e208',
									'operator' => '==',
									'value' => 'redirect',
								),
								array(
									'field' => 'field_66895376e1d81',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'https://',
					),
					array(
						'key' => 'field_66895ea1c1062',
						'label' => 'Notification',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 1,
						'multi_expand' => 1,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_66895ec6c1063',
						'label' => 'Site Admin Email',
						'name' => 'admin_email',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Enabled',
						'ui_off_text' => 'Disabled',
						'ui' => 1,
					),
					array(
						'key' => 'field_669eb7e04224d',
						'label' => 'Admin Template',
						'name' => 'admin_template',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66895ec6c1063',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'All Fields',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 1,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_66895efdc1064',
						'label' => 'Confirmation Email',
						'name' => 'confirmation_email',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => 'Form must have an Email field.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Enabled',
						'ui_off_text' => 'Disabled',
						'ui' => 1,
					),
					array(
						'key' => 'field_669eb8184224e',
						'label' => 'Confirmation Template',
						'name' => 'confirmation_template',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66895efdc1064',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'All Fields',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 1,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_66895f4bc1065',
						'label' => 'Custom Email',
						'name' => 'custom_email',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui_on_text' => 'Enabled',
						'ui_off_text' => 'Disabled',
						'ui' => 1,
					),
					array(
						'key' => 'field_66895f71c1066',
						'label' => 'Email Recipient',
						'name' => 'email_recipient',
						'aria-label' => '',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66895f4bc1065',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'name@domain.com',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_669eb8394224f',
						'label' => 'Custom Template',
						'name' => 'custom_template',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66895f4bc1065',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'All Fields',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 1,
						'ajax' => 0,
						'placeholder' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/form',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_669ea8d6ef54a',
				'title' => 'Block: Form Data',
				'fields' => array(
					array(
						'key' => 'field_669ea8d7298be',
						'label' => 'Form Field',
						'name' => 'form_field',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'Select a Field',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_669eb519e254c',
						'label' => 'Label',
						'name' => 'show_label',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Show',
						'ui_off_text' => 'Hide',
						'ui' => 1,
					),
					array(
						'key' => 'field_669eb53ce254d',
						'label' => 'Value',
						'name' => 'show_value',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Show',
						'ui_off_text' => 'Hide',
						'ui' => 1,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/form-data',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_66a7b9112a9b3',
				'title' => 'Block: Form Meta',
				'fields' => array(
					array(
						'key' => 'field_66a7b91132f2d',
						'label' => 'Meta Field',
						'name' => 'meta_field',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'Select Meta',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_66a7b91133327',
						'label' => 'Label',
						'name' => 'show_label',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Show',
						'ui_off_text' => 'Hide',
						'ui' => 1,
					),
					array(
						'key' => 'field_66a7b9113370e',
						'label' => 'Value',
						'name' => 'show_value',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Show',
						'ui_off_text' => 'Hide',
						'ui' => 1,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/form-meta',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_66970a1373563',
				'title' => 'Block: Select',
				'fields' => array(
					array(
						'key' => 'field_66970a1340d39',
						'label' => 'Allow Multiple',
						'name' => 'allow_multiple',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/select',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_66903c8f9103f',
				'title' => 'Block: Checkbox',
				'fields' => array(
					array(
						'key' => 'field_66903fac1f7c1',
						'label' => 'Checkbox Value',
						'name' => 'checkbox_value',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui_on_text' => 'Custom',
						'ui_off_text' => 'Use Label',
						'ui' => 1,
					),
					array(
						'key' => 'field_66903c90f056e',
						'label' => 'Value',
						'name' => 'value',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66903fac1f7c1',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'maxlength' => '',
						'placeholder' => 'Value when checked',
						'prepend' => '',
						'append' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/checkbox',
						),
					),
				),
				'menu_order' => 7,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_66832bf2f293a',
				'title' => 'Block: Input',
				'fields' => array(
					array(
						'key' => 'field_66832bf3c10aa',
						'label' => 'Input Type',
						'name' => 'type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'text' => 'Text',
							'email' => 'Email',
							'url' => 'URL',
							'tel' => 'Phone',
							'number' => 'Number',
							'password' => 'Password',
							'file' => 'File/Upload',
							'datetime-local' => 'Date/Time',
							'date' => 'Date',
							'time' => 'Time',
							'color' => 'Color Picker',
							'hidden' => 'Hidden',
						),
						'default_value' => 'text',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_669718dcc6615',
						'label' => 'Default Value',
						'name' => 'default_value',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_66886c0865624',
						'label' => 'Max Length',
						'name' => 'maxlength',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_66848acde5856',
						'label' => 'Controls',
						'name' => 'controls',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66832bf3c10aa',
									'operator' => '==',
									'value' => 'number',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => 'Enabled',
						'ui_off_text' => 'Disabled',
						'ui' => 1,
					),
					array(
						'key' => 'field_668865b10c6a5',
						'label' => 'Controls Settings',
						'name' => 'controls_settings',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_66832bf3c10aa',
									'operator' => '==',
									'value' => 'number',
								),
								array(
									'field' => 'field_66848acde5856',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_668865d10c6a7',
								'label' => 'Min',
								'name' => 'min',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33.33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_668865ef0c6a8',
								'label' => 'Max',
								'name' => 'max',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33.33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6688660c0c6a9',
								'label' => 'Step',
								'name' => 'step',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33.33',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/input',
						),
					),
				),
				'menu_order' => 10,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_668478504f2b5',
				'title' => 'Options',
				'fields' => array(
					array(
						'key' => 'field_66847850b53b2',
						'label' => 'Options',
						'name' => 'options',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Option',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_668478b1b53b6',
								'label' => 'Default',
								'name' => 'default',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
								'parent_repeater' => 'field_66847850b53b2',
							),
							array(
								'key' => 'field_66847892b53b5',
								'label' => 'Custom',
								'name' => 'custom',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
								'parent_repeater' => 'field_66847850b53b2',
							),
							array(
								'key' => 'field_66847869b53b3',
								'label' => 'Option',
								'name' => 'label',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66847850b53b2',
							),
							array(
								'key' => 'field_66847882b53b4',
								'label' => 'Value',
								'name' => 'value',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_66847892b53b5',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66847850b53b2',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/select',
						),
					),
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/radios',
						),
					),
				),
				'menu_order' => 10,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );

			acf_add_local_field_group( array(
				'key' => 'group_668c18f9290d7',
				'title' => 'Conditional Logic',
				'fields' => array(
					array(
						'key' => 'field_668c18f9beb53',
						'label' => 'Conditional Logic',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 1,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_668c1944ef703',
						'label' => '',
						'name' => 'enable_conditional_logic',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui_on_text' => 'Enabled',
						'ui_off_text' => 'Disabled',
						'ui' => 1,
					),
					array(
						'key' => 'field_668c1a238cccd',
						'label' => 'Conditional Logic',
						'name' => 'conditional_logic',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_668c1944ef703',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Condition',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_668c1a578ccce',
								'label' => 'Action',
								'name' => 'action',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'show' => 'Show',
									'hide' => 'Hide',
									'enable' => 'Enable',
									'disable' => 'Disable',
								),
								'default_value' => 'show',
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_668c1a238cccd',
							),
							array(
								'key' => 'field_668c1b138ccd0',
								'label' => 'When this field',
								'name' => 'field',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'-' => 'N/A',
								),
								'default_value' => '-',
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_668c1a238cccd',
							),
							array(
								'key' => 'field_668c1aaa8cccf',
								'label' => 'Meets this requirement',
								'name' => 'condition',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'isnotempty' => 'Has any value',
									'isempty' => 'Has no value',
									'is' => 'Has specific value',
									'isnot' => 'Does not have specific value',
									'greaterthan' => 'Is greater than',
									'lessthan' => 'Is less than',
									'contains' => 'Contains',
									'doesnotcontain' => 'Does not contain',
									'beginswith' => 'Begins With',
									'doesnotbeginwith' => 'Does not begin with',
								),
								'default_value' => 'not_empty',
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_668c1a238cccd',
							),
							array(
								'key' => 'field_668c1bf3f5729',
								'label' => 'Value',
								'name' => 'value',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_668c1aaa8cccf',
											'operator' => '!=',
											'value' => 'isnotempty',
										),
										array(
											'field' => 'field_668c1aaa8cccf',
											'operator' => '!=',
											'value' => 'isempty',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_668c1a238cccd',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/input',
						),
					),
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/radios',
						),
					),
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/select',
						),
					),
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/textarea',
						),
					),
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/submit',
						),
					),
				),
				'menu_order' => 90,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			) );
		} );
	}
);
